**Numpy**

In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)


import numpy as np

In [2]:
#### 2. Print the numpy version (★☆☆)

print(np.__version__)

1.22.4


In [4]:
#### 3. Create a null vector of size 10 (★☆☆)
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#### 4. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#### 5. Create a vector with values ranging from 10 to 49 (★☆☆)


Z = np.arange(10,50)
print(Z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#### 6. Reverse a vector (first element becomes last) (★☆☆)


Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
#### 7. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)


Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#### 8. Create a 3x3 identity matrix (★☆☆)


Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#### 9. Create a 3x3x3 array with random values (★☆☆)


Z = np.random.random((3,3,3))
print(Z)

[[[0.3393393  0.38955215 0.31916157]
  [0.89672308 0.8184816  0.17329884]
  [0.44133046 0.65343714 0.30509287]]

 [[0.07266254 0.63660616 0.07412223]
  [0.42346838 0.02125015 0.26751119]
  [0.44333838 0.72354351 0.71120106]]

 [[0.02578993 0.49837841 0.61244591]
  [0.02070731 0.41402642 0.38802938]
  [0.62132181 0.57269815 0.03277043]]]


In [12]:
#### 10. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.014293749158363012 0.9972772014827316


In [13]:
#### 11. Create a random vector of size 30 and find the mean value (★☆☆)


Z = np.random.random(30)
m = Z.mean()
print(m)

0.3902750402978416


In [14]:
#### 12. Normalize a 5x5 random matrix (★☆☆)


Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.82741414 -0.03455023 -0.39997443 -0.19609879  2.08910757]
 [ 1.37198154 -0.06737964  0.31973122  0.46925907 -1.43431096]
 [-0.90027926  1.33813938 -1.07889352 -1.24652734  1.39263992]
 [-1.56092633  1.7509611  -0.68426177  0.11249501 -0.0712828 ]
 [-0.84620314  0.48626979 -1.05479763 -0.2503689  -0.33214401]]


In [15]:
#### 13. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [17]:
#### 14. How to find common values between two arrays? (★☆☆)


Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 5 6 7 8 9]


In [19]:
#### 15. How to get the dates of yesterday, today and tomorrow? (★☆☆)


yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [20]:
#### 16. How to get all the dates corresponding to the month of July 2016? (★★☆)


Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


Pandas

In [21]:
import pandas as pd

In [22]:
print(pd.__version__)

1.3.5


In [ ]:
df = pd.read_csv("./data_0000.csv")

In [ ]:
# View the first five rows of data
df.head()


In [ ]:
print(f"The DataFrame contains {len(df)} observations and {len(df.columns)} columns.")


In [ ]:
print(f"The youngest respondent is {df.age.min()} years old.")
print(f"The oldest respondent is {df.age.max()} years old.")

In [ ]:
print(f"The average respondent watches TV news {df.TVnews.mean():.1f} days a week.")


In [ ]:
# You could also extract all the requested information using the .describe() method.
print(df.describe())

In [ ]:
# View data types and if there any missing values.
df.info()

In [ ]:
# Rename 'educ' column.
df = df.rename(columns={'educ': 'education'})

In [ ]:
def get_party(df):
  """
    returns respondent's political party based on PID
  """

  if df['PID'] < 2:
    return "Democrat"
  elif df['PID'] > 4:
    return "Republican"
  else:
    return "Independent"

# Apply the function to the df and save to a new column 'party.'
df['party'] = df.apply(get_party, axis = 1)

In [ ]:
def get_agegroup(df):
  """
    returns age bracket string dependent on respondent's exact age (integer)
  """

  if df['age'] < 25:
    return "18-24"
  elif df['age'] < 35:
    return "25-34"
  elif df['age'] < 45:
    return "35-44"
  elif df['age'] < 55:
    return "45-54"
  elif df['age'] < 65:
    return "55-64"
  else:
    return "65 and over"

# Apply the function to the df and save to new column 'age_group.'
df['age_group'] = df.apply(get_agegroup, axis = 1)

In [ ]:

ClModRep = df[df['ClinLR'] >= 4]

print(f"{len(ClModRep)} respondents have the impression that Bill Clinton is moderate or conservative.")

ClModRep_filtered = ClModRep[(ClModRep['income'] < 20) & (ClModRep['education'] > 3)]
print(f"Among the {len(ClModRep)} respondents have the impression that Bill Clinton is moderate or conservative, {len(ClModRep_filtered)} ({len(ClModRep_filtered)/len(ClModRep):.2f}%) earn less than $50,000 and attended at least some college.")

In [ ]:
# group df by age_group variable and calculate means for each columns
avg_by_age = df.groupby(["age_group"]).mean()

# print mean values of each age group for selected columns and sort accordingly
print(avg_by_age['selfLR'].sort_values(ascending = False))
print(avg_by_age['TVnews'].sort_values(ascending = True)) 

In [ ]:
income_quants = list(df['income'].quantile(q=[0.2, 0.4, 0.6, 0.8, 1]))

def get_income_quant(df):
  """
    Return quantile group based on respondent income.
  """

  if df['income'] <= income_quants[0]:
    return "Q1"
  elif df['income'] <= income_quants[1]:
    return "Q2"
  elif df['income'] <= income_quants[2]:
    return "Q3"
  elif df["income"] <= income_quants[3]:
    return "Q4"
  else:
    return "Q5"

# Apply it to the df and make a new column
df['income_quant'] = df.apply(get_income_quant, axis=1)

**ML & Scikit Learn**

In [23]:
import pandas as pd

In [24]:
import numpy as np

In [ ]:
df = pd.read_csv("./data_0001.csv")

In [ ]:
df.head()

In [ ]:
print(data.isnull().sum())

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
figure = px.scatter(data_frame = data, x="Sales",
                    y="TV", size="TV", trendline="ols")
figure.show()

In [ ]:
figure = px.scatter(data_frame = data, x="Sales",
                    y="Newspaper", size="Newspaper", trendline="ols")
figure.show()

In [ ]:
figure = px.scatter(data_frame = data, x="Sales",
                    y="Radio", size="Radio", trendline="ols")
figure.show()

In [ ]:
correlation = data.corr()
print(correlation["Sales"].sort_values(ascending=False))

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
x = np.array(data.drop(["Sales"], 1))
y = np.array(data["Sales"])
xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.2, 
                                                random_state=42)

In [ ]:
model = LinearRegression()
model.fit(xtrain, ytrain)
print(model.score(xtest, ytest))

In [ ]:
#features = [[TV, Radio, Newspaper]]
features = np.array([[230.1, 37.8, 69.2]])
print(model.predict(features))